apiVersion: 1
datasources:
  - name: POSTGRES_NAME
    type: postgres
    url: postgres
    user: POSTGRES_USER
    secureJsonData:
      password: POSTGRES_PASSWORD
    isDefault: true
    jsonData:
      database: POSTGRES_NAME
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+