version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: postgres_container
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      PGDATA: /var/lib/postgresql/data
    volumes:
      - path/to/your/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: ../
    container_name: fastapi_container
    environment: 
      DB_HOST: postgres
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres


#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana_container
#    volumes:
#      - ./datasources.yaml:/../../../etc/grafana/provisioning/datasources/datasources.yaml
#      - ./dashboard.yaml:/../../../etc/grafana/provisioning/dashboards/dashboard.yaml
#      - ../generator/generated_output/dashboards:/../../../var/lib/grafana/dashboards
#    ports:
#      - "3000:3000"
#    depends_on:
#      - postgres
#      - fastapi
#    environment:
#      GF_DATABASE_TYPE: postgres
#      GF_DATABASE_HOST: postgres
#      GF_DATABASE_PORT: 5432
#      GF_DATABASE_NAME: aaron
#      GF_DATABASE_USER: aaron
#      GF_DATABASE_PASSWORD: aaron
#    restart: always


volumes:
  postgres_data:
  grafana_data:
