version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: postgres_container
    environment:
      POSTGRES_DB: aaron
      POSTGRES_USER: aaron
      POSTGRES_PASSWORD: aaron
      PGDATA: /var/lib/postgresql/data
    volumes:
      - C:/Users/conrardy/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: ../
    container_name: fastapi_container
    environment: 
      DB_HOST: postgres
      DB_USER: aaron
      DB_PASSWORD: aaron
      DB_NAME: aaron
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: a
    ports:
      - "82:80"
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:
